# Generated by Django 3.2.16 on 2022-10-18 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_order_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
