# Generated by Django 3.2.16 on 2022-10-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_order_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default='0', help_text='Согласие на обработку персональных данных'),
        ),
    ]
