# Generated by Django 3.2.16 on 2022-10-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_user_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='consent',
        ),
    ]
