# Generated by Django 4.1.2 on 2022-10-18 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_alter_user_email_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя должно состоять из кириллицы', regex='^[А-Яа-я -]*$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Отчество пользователя должно состоять из кириллицы', regex='^[А-Яа-я -]*$')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Фамилия пользователя должно состоять из кириллицы', regex='^[А-Яа-я -]*$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя должно состоять только из латиницы', regex='^[A-Za-z -]*$')], verbose_name='Логин'),
        ),
    ]
