# Generated by Django 3.2.16 on 2022-10-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_alter_user_name_alter_user_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий', max_length=1000),
        ),
    ]
