# Generated by Django 3.2.16 on 2022-10-19 05:40

import django.core.validators
from django.db import migrations, models
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=studio.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
