# Generated by Django 3.2.16 on 2022-10-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_auto_20221022_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='img',
        ),
    ]
