# Generated by Django 3.2.16 on 2022-10-22 07:06

import django.core.validators
from django.db import migrations, models
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_remove_order_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_file',
        ),
        migrations.AddField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=studio.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
