# Generated by Django 3.2.16 on 2022-10-22 07:12

import django.core.validators
from django.db import migrations, models
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_auto_20221022_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_file',
            field=models.ImageField(max_length=200, null=True, upload_to=studio.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
